// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaccxooevufqeywvxlkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhY2N4b29ldnVmcWV5d3Z4bGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDcyNTQsImV4cCI6MjA3MTk4MzI1NH0.hjCiYJjw4-fsK2hDcL8y49zt2eEQUtL5d2JJQ6qC0gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});